//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int AdresID { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public string Cadde_Sokak { get; set; }
        public int Numara { get; set; }
        public int KullaniciID { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
