//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fis()
        {
            this.FisUrun = new HashSet<FisUrun>();
        }
    
        public int FisID { get; set; }
        public decimal ToplamTutar { get; set; }
        public decimal İndirimliOdenenTutar { get; set; }
        public decimal KrediKartiNo { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public string Cadde_Sokak { get; set; }
        public int Numara { get; set; }
        public string IletisimMaili { get; set; }
        public int KullaniciID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FisUrun> FisUrun { get; set; }
    }
}
