//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renk
    {
        public int BarkodNo { get; set; }
        public string Renk1 { get; set; }
        public string Resim { get; set; }
    
        public virtual Urun Urun { get; set; }
    }
}
