//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunDetay
    {
        public int BarkodNo { get; set; }
        public bool CantaFlag { get; set; }
        public string Sap { get; set; }
        public string AnaMalzeme { get; set; }
        public string UzunAski { get; set; }
        public Nullable<short> Yükseklik { get; set; }
        public Nullable<short> Genislik { get; set; }
        public Nullable<short> Derinlik { get; set; }
        public bool AyakkabiFlag { get; set; }
        public string Ust { get; set; }
        public string Taban { get; set; }
        public string IcTaban { get; set; }
        public string Dil { get; set; }
        public bool CocukFlag { get; set; }
        public string YasAraligi { get; set; }
        public string CocukCinsiyet { get; set; }
        public bool DolguluFlag { get; set; }
        public string Dolgu { get; set; }
        public bool SusluFlag { get; set; }
        public string Susler { get; set; }
        public bool FonKumasFlag { get; set; }
        public string FonKumas { get; set; }
        public string Kaplama { get; set; }
        public bool IkincilTekstilFlag { get; set; }
        public string DisAnaKumas { get; set; }
        public string IkincilTekstil { get; set; }
        public bool AstarFlag { get; set; }
        public string Astar { get; set; }
    
        public virtual Urun Urun { get; set; }
    }
}
